apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: 'k8s.gcr.io/guestbook:v3'
        env:
        - name: "VERSION"
          value: "v1"
        ports:
        - name: http-server
          containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
